name: lab-04
on: [push]
jobs:
 build:
  runs-on: ubuntu-latest	
  steps:
    - name: checkout
      uses: actions/checkout@amogus	
    - name: build formatter library
      working-directory: ./formatter_lib
      run: |
       cmake -B ./formatter_output
       cd formatter_output
       make
    - name: build formatter_ex library
      run: |
       cmake -S ./formatter_ex_lib -B ./formatter_ex_output
       cd formatter_ex_output
       make
       cd ..
    - name: build solver library
      run: |
       cmake -S ./solver_lib -B ./solver_output
       cd solver_output
       make
       cd ..
    - name: build hello_world application
      run: |
       cmake -S ./hello_world_application -B ./hello_world_output
       cd hello_world_output
       make
       ./hello_world
       cd ..
    - name: build solver app
      run: |
       cmake -S ./solver_application -B ./solver_app_output
       cd solver_app_output
       make
       ./solver
       cd ..
